<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SchedulesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('jadwal')->insert([
            [
                'id_jadwal' => 1,
                'day' => 'Senin',
                'subject' => '♡. Bahasa Indonesia',
                'jp' => '07.15 - 09.15',
                'teacher' => 'Ibu Tita',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 2,
                'day' => 'Senin',
                'subject' => '♡. Pai',
                'jp' => '09.30 - 10.10',
                'teacher' => 'Ibu Laela',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 3,
                'day' => 'Senin',
                'subject' => '♡. Basis Data',
                'jp' => '10.10 - 14.20',
                'teacher' => 'Ibu Indri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 4,
                'day' => 'Senin',
                'subject' => '♡. B. Jerman',
                'jp' => '14.20 - 15.00',
                'teacher' => 'Pak Abdul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_jadwal' => 5,
                'day' => 'Selasa',
                'subject' => '♡. Pai',
                'jp' => '07.15 - 08.35',
                'teacher' => 'Ibu Laela',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 6,
                'day' => 'Selasa',
                'subject' => '♡. Matematika',
                'jp' => '08.35 - 10.10',
                'teacher' => 'Pak Acun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 7,
                'day' => 'Selasa',
                'subject' => '♡. Pancasila',
                'jp' => '10.10 - 11.30',
                'teacher' => 'Ibu Vanny',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 8,
                'day' => 'Selasa',
                'subject' => 'Psikotes',
                'jp' => '11.30 - 13.40',
                'teacher' => 'Ibu Putri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 9,
                'day' => 'Selasa',
                'subject' => 'Pjok',
                'jp' => '13.40 - 15.00',
                'teacher' => 'Pak Asep',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        
            [
                'id_jadwal' => 10,
                'day' => 'Rabu',
                'subject' => '♡. Kewirausahaan',
                'jp' => '07.15 - 11.30',
                'teacher' => 'Pak Gunawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 11,
                'day' => 'Rabu',
                'subject' => 'B.Inggris',
                'jp' => '09.30 - 10.10',
                'teacher' => 'Mrs. Monica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 12,
                'day' => 'Rabu',
                'subject' => '♡. Kewirausahaan',
                'jp' => '10.10 - 11.30',
                'teacher' => 'Pak Gunawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 13,
                'day' => 'Rabu',
                'subject' => '♡. Perangkat Bergerak',
                'jp' => '11.30 - 15.00',
                'teacher' => 'Pak Gunawan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_jadwal' => 14,
                'day' => 'Kamis',
                'subject' => '♡. Pemograman Berbasis Teks, Grafis, dan Multimedia',
                'jp' => ' 07.15 - 11.30',
                'teacher' => 'Ibu Dhian',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 15,
                'day' => 'Kamis',
                'subject' => '♡. B. Jerman',
                'jp' => '11.30 - 12.10',
                'teacher' => 'Pak Abdul',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 16,
                'day' => 'Kamis',
                'subject' => '♡ B.Inggris',
                'jp' => '13.00 - 15.00',
                'teacher' => 'Mrs. Monica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 17,
                'day' => 'Jumat',
                'subject' =>'♡. Pembimbingan Walas',
                'jp' => '06.30 - 07.15',
                'teacher' => 'Pak Gunawan Busyaeri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 18,
                'day' => 'Jumat',
                'subject' => '♡. Pemograman Web',
                'jp' => '07.15 - 09.15',
                'teacher' => 'Pak Jumadi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 19,
                'day' => 'Jumat',
                'subject' => '♡. Matematika',
                'jp' => '09.30 - 10.10',
                'teacher' => 'Pak Acun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_jadwal' => 20,
                'day' => 'Jumat',
                'subject' => 'Pemograman Web',
                'jp' => '10.10 - 14.20',
                'teacher' => '♡. Pak Jumadi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}